### ISSUE TITLE
Estimated wait time

### ISSUE THREAD

**Issue by justinpk** [mterwill/office-hours-help-queue#130] opened 2018-02-13 04:16 UTC
Add a part that allows students to see how long the estimated wait time is until they will be seen by an instructor (estimate based on number of people in queue, number of instructors on hand, and an estimated 5 minute one on one time per person).

**Comment by mterwill** [comment] 2018-03-15 12:44
Duplicate of #91.

**Closed by mterwill** 2018-03-15 12:44 UTC
